### ISSUE TITLE
Are the README.md Steps Still Valid?

### ISSUE THREAD

**Issue by johnjvester** [adityanaag3/planning-poker-salesforce#13]
I have attempted to use this repository in both an existing Developer org (that I have been using since ~2015) as Package and using the SFDX commands in a scratch org.

- The package option always fails to show the option where I can select the card type and match up backlog items to a given game.  Going to the Host Planning Poker screen is merely a header.  I am logged in using the same user and I feel like I tried to install the package for Admins Only and for All Users with the same results.  I cannot get far enough to see if running anonymous clients in Heroku is going to work.

- The SFDX option allows me to start hosting a game in a scratch org and I can connect using Salesforce clients.  However, the Heroku logs show I am getting a 500 error when trying to connect to the scratch instance.  I am certain I have followed all the instructions, but feel like there is a step missing.  Here is an example of the Heroku logs:

I really would like to get this running, so that I can write a DZone.com article about how you have made a very practical Salesforce solution which can leverage Heroku as well.

```
2020-11-18T06:10:56.178649+00:00 heroku[router]: at=info method=GET path="/api/validateGameKey?gameKey=G2Fxr" host=jvc-planning-poker-heroku.herokuapp.com request_id=0e0b9dec-3b12-4ee1-8623-f8996f6da709 fwd="47.227.182.227" dyno=web.1 connect=1ms service=384ms status=500 bytes=486 protocol=https
2020-11-18T06:10:56.229105+00:00 heroku[router]: at=info method=GET path="/resources/icons/utility-sprite/svg/symbols.svg" host=jvc-planning-poker-heroku.herokuapp.com request_id=1c1923a3-d88b-4236-85f8-065e148f1e0c fwd="47.227.182.227" dyno=web.1 connect=3ms service=3ms status=304 bytes=432 protocol=https
```

Also, one thing that is not clear for me is the required `SF_NAMESPACE` for the SFDX option.  Looking at the referenced JSON, it looks like the value should be set to null.  Is that correct?  (I have tried setting this to nothing (`null`) and also leaving the default - neither changed what I was seeing in the Heroku logs)

Thank you for your time!
jv

**Comment by adityanaag3** [comment]
Hey - That is strange - I just installed the app on a Trailhead Playground using the link on the Readme file, and it works fine. The Heroku app works too. Can you try creating a new org and give it a try? Or we can get onto a call to figure it out.

Regarding the SF_NAMESPACE - For the SFDX option, you can leave it blank by default, but even with SFDX you have the option to put a namespace in the sfdx-project.json file, and once you push the files to a scratch org, the files take the namespace specified.

**Comment by johnjvester** [comment]
Using a Trailhead Playground and the package option worked for me.  Thank you so much for your time!
